name: Lint & Test

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

jobs:
  python:
    name: Python Lint & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r ingestion-service/src/requirements.txt
          pip install -r embedding-service/src/requirements.txt
          pip install pytest pytest-asyncio flake8 black mypy httpx

      - name: Lint with flake8
        run: |
          source .venv/bin/activate
          flake8 .

      - name: Type-check with mypy
        run: |
          source .venv/bin/activate
          mypy .

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest -q

  go:
    name: Go Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install linters
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Lint with golangci-lint
        run: golangci-lint run ./search-api/...

      - name: Run Go tests
        run: go test ./search-api/... -v

  node:
    name: JS/TS Lint & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint & Test
        run: |
          npm run lint
          npm test
